// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"blog/dal/model"
)

func newComments(db *gorm.DB, opts ...gen.DOOption) comments {
	_comments := comments{}

	_comments.commentsDo.UseDB(db, opts...)
	_comments.commentsDo.UseModel(&model.Comments{})

	tableName := _comments.commentsDo.TableName()
	_comments.ALL = field.NewAsterisk(tableName)
	_comments.Coid = field.NewInt64(tableName, "coid")
	_comments.Type = field.NewInt(tableName, "type")
	_comments.ParentId = field.NewInt64(tableName, "parent_id")
	_comments.Cid = field.NewInt64(tableName, "cid")
	_comments.Author = field.NewString(tableName, "author")
	_comments.AuthorId = field.NewInt64(tableName, "author_id")
	_comments.OwnerId = field.NewInt64(tableName, "owner_id")
	_comments.Mail = field.NewString(tableName, "mail")
	_comments.Url = field.NewString(tableName, "url")
	_comments.Ip = field.NewString(tableName, "ip")
	_comments.Agent = field.NewString(tableName, "agent")
	_comments.Text = field.NewString(tableName, "text")
	_comments.Status = field.NewInt(tableName, "status")
	_comments.CreatedAt = field.NewInt64(tableName, "created_at")

	_comments.fillFieldMap()

	return _comments
}

type comments struct {
	commentsDo commentsDo

	ALL       field.Asterisk
	Coid      field.Int64
	Type      field.Int
	ParentId  field.Int64
	Cid       field.Int64
	Author    field.String
	AuthorId  field.Int64
	OwnerId   field.Int64
	Mail      field.String
	Url       field.String
	Ip        field.String
	Agent     field.String
	Text      field.String
	Status    field.Int
	CreatedAt field.Int64

	fieldMap map[string]field.Expr
}

func (c comments) Table(newTableName string) *comments {
	c.commentsDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c comments) As(alias string) *comments {
	c.commentsDo.DO = *(c.commentsDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *comments) updateTableName(table string) *comments {
	c.ALL = field.NewAsterisk(table)
	c.Coid = field.NewInt64(table, "coid")
	c.Type = field.NewInt(table, "type")
	c.ParentId = field.NewInt64(table, "parent_id")
	c.Cid = field.NewInt64(table, "cid")
	c.Author = field.NewString(table, "author")
	c.AuthorId = field.NewInt64(table, "author_id")
	c.OwnerId = field.NewInt64(table, "owner_id")
	c.Mail = field.NewString(table, "mail")
	c.Url = field.NewString(table, "url")
	c.Ip = field.NewString(table, "ip")
	c.Agent = field.NewString(table, "agent")
	c.Text = field.NewString(table, "text")
	c.Status = field.NewInt(table, "status")
	c.CreatedAt = field.NewInt64(table, "created_at")

	c.fillFieldMap()

	return c
}

func (c *comments) WithContext(ctx context.Context) *commentsDo { return c.commentsDo.WithContext(ctx) }

func (c comments) TableName() string { return c.commentsDo.TableName() }

func (c comments) Alias() string { return c.commentsDo.Alias() }

func (c comments) Columns(cols ...field.Expr) gen.Columns { return c.commentsDo.Columns(cols...) }

func (c *comments) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *comments) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 14)
	c.fieldMap["coid"] = c.Coid
	c.fieldMap["type"] = c.Type
	c.fieldMap["parent_id"] = c.ParentId
	c.fieldMap["cid"] = c.Cid
	c.fieldMap["author"] = c.Author
	c.fieldMap["author_id"] = c.AuthorId
	c.fieldMap["owner_id"] = c.OwnerId
	c.fieldMap["mail"] = c.Mail
	c.fieldMap["url"] = c.Url
	c.fieldMap["ip"] = c.Ip
	c.fieldMap["agent"] = c.Agent
	c.fieldMap["text"] = c.Text
	c.fieldMap["status"] = c.Status
	c.fieldMap["created_at"] = c.CreatedAt
}

func (c comments) clone(db *gorm.DB) comments {
	c.commentsDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c comments) replaceDB(db *gorm.DB) comments {
	c.commentsDo.ReplaceDB(db)
	return c
}

type commentsDo struct{ gen.DO }

func (c commentsDo) Debug() *commentsDo {
	return c.withDO(c.DO.Debug())
}

func (c commentsDo) WithContext(ctx context.Context) *commentsDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c commentsDo) ReadDB() *commentsDo {
	return c.Clauses(dbresolver.Read)
}

func (c commentsDo) WriteDB() *commentsDo {
	return c.Clauses(dbresolver.Write)
}

func (c commentsDo) Session(config *gorm.Session) *commentsDo {
	return c.withDO(c.DO.Session(config))
}

func (c commentsDo) Clauses(conds ...clause.Expression) *commentsDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c commentsDo) Returning(value interface{}, columns ...string) *commentsDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c commentsDo) Not(conds ...gen.Condition) *commentsDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c commentsDo) Or(conds ...gen.Condition) *commentsDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c commentsDo) Select(conds ...field.Expr) *commentsDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c commentsDo) Where(conds ...gen.Condition) *commentsDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c commentsDo) Order(conds ...field.Expr) *commentsDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c commentsDo) Distinct(cols ...field.Expr) *commentsDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c commentsDo) Omit(cols ...field.Expr) *commentsDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c commentsDo) Join(table schema.Tabler, on ...field.Expr) *commentsDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c commentsDo) LeftJoin(table schema.Tabler, on ...field.Expr) *commentsDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c commentsDo) RightJoin(table schema.Tabler, on ...field.Expr) *commentsDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c commentsDo) Group(cols ...field.Expr) *commentsDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c commentsDo) Having(conds ...gen.Condition) *commentsDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c commentsDo) Limit(limit int) *commentsDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c commentsDo) Offset(offset int) *commentsDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c commentsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *commentsDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c commentsDo) Unscoped() *commentsDo {
	return c.withDO(c.DO.Unscoped())
}

func (c commentsDo) Create(values ...*model.Comments) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c commentsDo) CreateInBatches(values []*model.Comments, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c commentsDo) Save(values ...*model.Comments) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c commentsDo) First() (*model.Comments, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Comments), nil
	}
}

func (c commentsDo) Take() (*model.Comments, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Comments), nil
	}
}

func (c commentsDo) Last() (*model.Comments, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Comments), nil
	}
}

func (c commentsDo) Find() ([]*model.Comments, error) {
	result, err := c.DO.Find()
	return result.([]*model.Comments), err
}

func (c commentsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Comments, err error) {
	buf := make([]*model.Comments, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c commentsDo) FindInBatches(result *[]*model.Comments, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c commentsDo) Attrs(attrs ...field.AssignExpr) *commentsDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c commentsDo) Assign(attrs ...field.AssignExpr) *commentsDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c commentsDo) Joins(fields ...field.RelationField) *commentsDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c commentsDo) Preload(fields ...field.RelationField) *commentsDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c commentsDo) FirstOrInit() (*model.Comments, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Comments), nil
	}
}

func (c commentsDo) FirstOrCreate() (*model.Comments, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Comments), nil
	}
}

func (c commentsDo) FindByPage(offset int, limit int) (result []*model.Comments, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c commentsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c commentsDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c commentsDo) Delete(models ...*model.Comments) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *commentsDo) withDO(do gen.Dao) *commentsDo {
	c.DO = *do.(*gen.DO)
	return c
}
