// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"blog/dal/model"
)

func newContents(db *gorm.DB, opts ...gen.DOOption) contents {
	_contents := contents{}

	_contents.contentsDo.UseDB(db, opts...)
	_contents.contentsDo.UseModel(&model.Contents{})

	tableName := _contents.contentsDo.TableName()
	_contents.ALL = field.NewAsterisk(tableName)
	_contents.Cid = field.NewInt64(tableName, "cid")
	_contents.Type = field.NewInt(tableName, "type")
	_contents.Title = field.NewString(tableName, "title")
	_contents.Slug = field.NewString(tableName, "slug")
	_contents.Text = field.NewString(tableName, "text")
	_contents.AuthorId = field.NewInt64(tableName, "author_id")
	_contents.Status = field.NewInt(tableName, "status")
	_contents.Password = field.NewString(tableName, "password")
	_contents.CommentsNum = field.NewInt64(tableName, "comments_num")
	_contents.ViewsNum = field.NewInt64(tableName, "views_num")
	_contents.AllowComment = field.NewInt(tableName, "allow_comment")
	_contents.AllowPing = field.NewInt(tableName, "allow_ping")
	_contents.AllowFeed = field.NewInt(tableName, "allow_feed")
	_contents.CreatedAt = field.NewInt64(tableName, "created_at")
	_contents.UpdatedAt = field.NewInt64(tableName, "updated_at")

	_contents.fillFieldMap()

	return _contents
}

type contents struct {
	contentsDo contentsDo

	ALL          field.Asterisk
	Cid          field.Int64
	Type         field.Int
	Title        field.String
	Slug         field.String
	Text         field.String
	AuthorId     field.Int64
	Status       field.Int
	Password     field.String
	CommentsNum  field.Int64
	ViewsNum     field.Int64
	AllowComment field.Int
	AllowPing    field.Int
	AllowFeed    field.Int
	CreatedAt    field.Int64
	UpdatedAt    field.Int64

	fieldMap map[string]field.Expr
}

func (c contents) Table(newTableName string) *contents {
	c.contentsDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c contents) As(alias string) *contents {
	c.contentsDo.DO = *(c.contentsDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *contents) updateTableName(table string) *contents {
	c.ALL = field.NewAsterisk(table)
	c.Cid = field.NewInt64(table, "cid")
	c.Type = field.NewInt(table, "type")
	c.Title = field.NewString(table, "title")
	c.Slug = field.NewString(table, "slug")
	c.Text = field.NewString(table, "text")
	c.AuthorId = field.NewInt64(table, "author_id")
	c.Status = field.NewInt(table, "status")
	c.Password = field.NewString(table, "password")
	c.CommentsNum = field.NewInt64(table, "comments_num")
	c.ViewsNum = field.NewInt64(table, "views_num")
	c.AllowComment = field.NewInt(table, "allow_comment")
	c.AllowPing = field.NewInt(table, "allow_ping")
	c.AllowFeed = field.NewInt(table, "allow_feed")
	c.CreatedAt = field.NewInt64(table, "created_at")
	c.UpdatedAt = field.NewInt64(table, "updated_at")

	c.fillFieldMap()

	return c
}

func (c *contents) WithContext(ctx context.Context) *contentsDo { return c.contentsDo.WithContext(ctx) }

func (c contents) TableName() string { return c.contentsDo.TableName() }

func (c contents) Alias() string { return c.contentsDo.Alias() }

func (c contents) Columns(cols ...field.Expr) gen.Columns { return c.contentsDo.Columns(cols...) }

func (c *contents) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *contents) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 15)
	c.fieldMap["cid"] = c.Cid
	c.fieldMap["type"] = c.Type
	c.fieldMap["title"] = c.Title
	c.fieldMap["slug"] = c.Slug
	c.fieldMap["text"] = c.Text
	c.fieldMap["author_id"] = c.AuthorId
	c.fieldMap["status"] = c.Status
	c.fieldMap["password"] = c.Password
	c.fieldMap["comments_num"] = c.CommentsNum
	c.fieldMap["views_num"] = c.ViewsNum
	c.fieldMap["allow_comment"] = c.AllowComment
	c.fieldMap["allow_ping"] = c.AllowPing
	c.fieldMap["allow_feed"] = c.AllowFeed
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
}

func (c contents) clone(db *gorm.DB) contents {
	c.contentsDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c contents) replaceDB(db *gorm.DB) contents {
	c.contentsDo.ReplaceDB(db)
	return c
}

type contentsDo struct{ gen.DO }

func (c contentsDo) Debug() *contentsDo {
	return c.withDO(c.DO.Debug())
}

func (c contentsDo) WithContext(ctx context.Context) *contentsDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c contentsDo) ReadDB() *contentsDo {
	return c.Clauses(dbresolver.Read)
}

func (c contentsDo) WriteDB() *contentsDo {
	return c.Clauses(dbresolver.Write)
}

func (c contentsDo) Session(config *gorm.Session) *contentsDo {
	return c.withDO(c.DO.Session(config))
}

func (c contentsDo) Clauses(conds ...clause.Expression) *contentsDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c contentsDo) Returning(value interface{}, columns ...string) *contentsDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c contentsDo) Not(conds ...gen.Condition) *contentsDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c contentsDo) Or(conds ...gen.Condition) *contentsDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c contentsDo) Select(conds ...field.Expr) *contentsDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c contentsDo) Where(conds ...gen.Condition) *contentsDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c contentsDo) Order(conds ...field.Expr) *contentsDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c contentsDo) Distinct(cols ...field.Expr) *contentsDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c contentsDo) Omit(cols ...field.Expr) *contentsDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c contentsDo) Join(table schema.Tabler, on ...field.Expr) *contentsDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c contentsDo) LeftJoin(table schema.Tabler, on ...field.Expr) *contentsDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c contentsDo) RightJoin(table schema.Tabler, on ...field.Expr) *contentsDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c contentsDo) Group(cols ...field.Expr) *contentsDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c contentsDo) Having(conds ...gen.Condition) *contentsDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c contentsDo) Limit(limit int) *contentsDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c contentsDo) Offset(offset int) *contentsDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c contentsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *contentsDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c contentsDo) Unscoped() *contentsDo {
	return c.withDO(c.DO.Unscoped())
}

func (c contentsDo) Create(values ...*model.Contents) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c contentsDo) CreateInBatches(values []*model.Contents, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c contentsDo) Save(values ...*model.Contents) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c contentsDo) First() (*model.Contents, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Contents), nil
	}
}

func (c contentsDo) Take() (*model.Contents, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Contents), nil
	}
}

func (c contentsDo) Last() (*model.Contents, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Contents), nil
	}
}

func (c contentsDo) Find() ([]*model.Contents, error) {
	result, err := c.DO.Find()
	return result.([]*model.Contents), err
}

func (c contentsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Contents, err error) {
	buf := make([]*model.Contents, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c contentsDo) FindInBatches(result *[]*model.Contents, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c contentsDo) Attrs(attrs ...field.AssignExpr) *contentsDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c contentsDo) Assign(attrs ...field.AssignExpr) *contentsDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c contentsDo) Joins(fields ...field.RelationField) *contentsDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c contentsDo) Preload(fields ...field.RelationField) *contentsDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c contentsDo) FirstOrInit() (*model.Contents, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Contents), nil
	}
}

func (c contentsDo) FirstOrCreate() (*model.Contents, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Contents), nil
	}
}

func (c contentsDo) FindByPage(offset int, limit int) (result []*model.Contents, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c contentsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c contentsDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c contentsDo) Delete(models ...*model.Contents) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *contentsDo) withDO(do gen.Dao) *contentsDo {
	c.DO = *do.(*gen.DO)
	return c
}
