// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:            db,
		Comments:      newComments(db, opts...),
		Config:        newConfig(db, opts...),
		Contents:      newContents(db, opts...),
		Links:         newLinks(db, opts...),
		Metas:         newMetas(db, opts...),
		Plugins:       newPlugins(db, opts...),
		Relationships: newRelationships(db, opts...),
		Templates:     newTemplates(db, opts...),
		Users:         newUsers(db, opts...),
		Views:         newViews(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Comments      comments
	Config        config
	Contents      contents
	Links         links
	Metas         metas
	Plugins       plugins
	Relationships relationships
	Templates     templates
	Users         users
	Views         views
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:            db,
		Comments:      q.Comments.clone(db),
		Config:        q.Config.clone(db),
		Contents:      q.Contents.clone(db),
		Links:         q.Links.clone(db),
		Metas:         q.Metas.clone(db),
		Plugins:       q.Plugins.clone(db),
		Relationships: q.Relationships.clone(db),
		Templates:     q.Templates.clone(db),
		Users:         q.Users.clone(db),
		Views:         q.Views.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:            db,
		Comments:      q.Comments.replaceDB(db),
		Config:        q.Config.replaceDB(db),
		Contents:      q.Contents.replaceDB(db),
		Links:         q.Links.replaceDB(db),
		Metas:         q.Metas.replaceDB(db),
		Plugins:       q.Plugins.replaceDB(db),
		Relationships: q.Relationships.replaceDB(db),
		Templates:     q.Templates.replaceDB(db),
		Users:         q.Users.replaceDB(db),
		Views:         q.Views.replaceDB(db),
	}
}

type queryCtx struct {
	Comments      *commentsDo
	Config        *configDo
	Contents      *contentsDo
	Links         *linksDo
	Metas         *metasDo
	Plugins       *pluginsDo
	Relationships *relationshipsDo
	Templates     *templatesDo
	Users         *usersDo
	Views         *viewsDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Comments:      q.Comments.WithContext(ctx),
		Config:        q.Config.WithContext(ctx),
		Contents:      q.Contents.WithContext(ctx),
		Links:         q.Links.WithContext(ctx),
		Metas:         q.Metas.WithContext(ctx),
		Plugins:       q.Plugins.WithContext(ctx),
		Relationships: q.Relationships.WithContext(ctx),
		Templates:     q.Templates.WithContext(ctx),
		Users:         q.Users.WithContext(ctx),
		Views:         q.Views.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
