// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"blog/dal/model"
)

func newMetas(db *gorm.DB, opts ...gen.DOOption) metas {
	_metas := metas{}

	_metas.metasDo.UseDB(db, opts...)
	_metas.metasDo.UseModel(&model.Metas{})

	tableName := _metas.metasDo.TableName()
	_metas.ALL = field.NewAsterisk(tableName)
	_metas.Mid = field.NewInt64(tableName, "mid")
	_metas.Name = field.NewString(tableName, "name")
	_metas.Icon = field.NewString(tableName, "icon")
	_metas.Slug = field.NewString(tableName, "slug")
	_metas.Type = field.NewInt(tableName, "type")
	_metas.Description = field.NewString(tableName, "description")
	_metas.Count = field.NewInt(tableName, "count")
	_metas.Sort = field.NewInt(tableName, "sort")

	_metas.fillFieldMap()

	return _metas
}

type metas struct {
	metasDo metasDo

	ALL         field.Asterisk
	Mid         field.Int64
	Name        field.String
	Icon        field.String
	Slug        field.String
	Type        field.Int
	Description field.String
	Count       field.Int
	Sort        field.Int

	fieldMap map[string]field.Expr
}

func (m metas) Table(newTableName string) *metas {
	m.metasDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m metas) As(alias string) *metas {
	m.metasDo.DO = *(m.metasDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *metas) updateTableName(table string) *metas {
	m.ALL = field.NewAsterisk(table)
	m.Mid = field.NewInt64(table, "mid")
	m.Name = field.NewString(table, "name")
	m.Icon = field.NewString(table, "icon")
	m.Slug = field.NewString(table, "slug")
	m.Type = field.NewInt(table, "type")
	m.Description = field.NewString(table, "description")
	m.Count = field.NewInt(table, "count")
	m.Sort = field.NewInt(table, "sort")

	m.fillFieldMap()

	return m
}

func (m *metas) WithContext(ctx context.Context) *metasDo { return m.metasDo.WithContext(ctx) }

func (m metas) TableName() string { return m.metasDo.TableName() }

func (m metas) Alias() string { return m.metasDo.Alias() }

func (m metas) Columns(cols ...field.Expr) gen.Columns { return m.metasDo.Columns(cols...) }

func (m *metas) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *metas) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 8)
	m.fieldMap["mid"] = m.Mid
	m.fieldMap["name"] = m.Name
	m.fieldMap["icon"] = m.Icon
	m.fieldMap["slug"] = m.Slug
	m.fieldMap["type"] = m.Type
	m.fieldMap["description"] = m.Description
	m.fieldMap["count"] = m.Count
	m.fieldMap["sort"] = m.Sort
}

func (m metas) clone(db *gorm.DB) metas {
	m.metasDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m metas) replaceDB(db *gorm.DB) metas {
	m.metasDo.ReplaceDB(db)
	return m
}

type metasDo struct{ gen.DO }

func (m metasDo) Debug() *metasDo {
	return m.withDO(m.DO.Debug())
}

func (m metasDo) WithContext(ctx context.Context) *metasDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m metasDo) ReadDB() *metasDo {
	return m.Clauses(dbresolver.Read)
}

func (m metasDo) WriteDB() *metasDo {
	return m.Clauses(dbresolver.Write)
}

func (m metasDo) Session(config *gorm.Session) *metasDo {
	return m.withDO(m.DO.Session(config))
}

func (m metasDo) Clauses(conds ...clause.Expression) *metasDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m metasDo) Returning(value interface{}, columns ...string) *metasDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m metasDo) Not(conds ...gen.Condition) *metasDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m metasDo) Or(conds ...gen.Condition) *metasDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m metasDo) Select(conds ...field.Expr) *metasDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m metasDo) Where(conds ...gen.Condition) *metasDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m metasDo) Order(conds ...field.Expr) *metasDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m metasDo) Distinct(cols ...field.Expr) *metasDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m metasDo) Omit(cols ...field.Expr) *metasDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m metasDo) Join(table schema.Tabler, on ...field.Expr) *metasDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m metasDo) LeftJoin(table schema.Tabler, on ...field.Expr) *metasDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m metasDo) RightJoin(table schema.Tabler, on ...field.Expr) *metasDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m metasDo) Group(cols ...field.Expr) *metasDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m metasDo) Having(conds ...gen.Condition) *metasDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m metasDo) Limit(limit int) *metasDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m metasDo) Offset(offset int) *metasDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m metasDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *metasDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m metasDo) Unscoped() *metasDo {
	return m.withDO(m.DO.Unscoped())
}

func (m metasDo) Create(values ...*model.Metas) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m metasDo) CreateInBatches(values []*model.Metas, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m metasDo) Save(values ...*model.Metas) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m metasDo) First() (*model.Metas, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Metas), nil
	}
}

func (m metasDo) Take() (*model.Metas, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Metas), nil
	}
}

func (m metasDo) Last() (*model.Metas, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Metas), nil
	}
}

func (m metasDo) Find() ([]*model.Metas, error) {
	result, err := m.DO.Find()
	return result.([]*model.Metas), err
}

func (m metasDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Metas, err error) {
	buf := make([]*model.Metas, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m metasDo) FindInBatches(result *[]*model.Metas, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m metasDo) Attrs(attrs ...field.AssignExpr) *metasDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m metasDo) Assign(attrs ...field.AssignExpr) *metasDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m metasDo) Joins(fields ...field.RelationField) *metasDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m metasDo) Preload(fields ...field.RelationField) *metasDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m metasDo) FirstOrInit() (*model.Metas, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Metas), nil
	}
}

func (m metasDo) FirstOrCreate() (*model.Metas, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Metas), nil
	}
}

func (m metasDo) FindByPage(offset int, limit int) (result []*model.Metas, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m metasDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m metasDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m metasDo) Delete(models ...*model.Metas) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *metasDo) withDO(do gen.Dao) *metasDo {
	m.DO = *do.(*gen.DO)
	return m
}
