// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"blog/dal/model"
)

func newPlugins(db *gorm.DB, opts ...gen.DOOption) plugins {
	_plugins := plugins{}

	_plugins.pluginsDo.UseDB(db, opts...)
	_plugins.pluginsDo.UseModel(&model.Plugins{})

	tableName := _plugins.pluginsDo.TableName()
	_plugins.ALL = field.NewAsterisk(tableName)
	_plugins.K = field.NewString(tableName, "k")
	_plugins.V = field.NewString(tableName, "v")

	_plugins.fillFieldMap()

	return _plugins
}

type plugins struct {
	pluginsDo pluginsDo

	ALL field.Asterisk
	K   field.String
	V   field.String

	fieldMap map[string]field.Expr
}

func (p plugins) Table(newTableName string) *plugins {
	p.pluginsDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p plugins) As(alias string) *plugins {
	p.pluginsDo.DO = *(p.pluginsDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *plugins) updateTableName(table string) *plugins {
	p.ALL = field.NewAsterisk(table)
	p.K = field.NewString(table, "k")
	p.V = field.NewString(table, "v")

	p.fillFieldMap()

	return p
}

func (p *plugins) WithContext(ctx context.Context) *pluginsDo { return p.pluginsDo.WithContext(ctx) }

func (p plugins) TableName() string { return p.pluginsDo.TableName() }

func (p plugins) Alias() string { return p.pluginsDo.Alias() }

func (p plugins) Columns(cols ...field.Expr) gen.Columns { return p.pluginsDo.Columns(cols...) }

func (p *plugins) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *plugins) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 2)
	p.fieldMap["k"] = p.K
	p.fieldMap["v"] = p.V
}

func (p plugins) clone(db *gorm.DB) plugins {
	p.pluginsDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p plugins) replaceDB(db *gorm.DB) plugins {
	p.pluginsDo.ReplaceDB(db)
	return p
}

type pluginsDo struct{ gen.DO }

func (p pluginsDo) Debug() *pluginsDo {
	return p.withDO(p.DO.Debug())
}

func (p pluginsDo) WithContext(ctx context.Context) *pluginsDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p pluginsDo) ReadDB() *pluginsDo {
	return p.Clauses(dbresolver.Read)
}

func (p pluginsDo) WriteDB() *pluginsDo {
	return p.Clauses(dbresolver.Write)
}

func (p pluginsDo) Session(config *gorm.Session) *pluginsDo {
	return p.withDO(p.DO.Session(config))
}

func (p pluginsDo) Clauses(conds ...clause.Expression) *pluginsDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p pluginsDo) Returning(value interface{}, columns ...string) *pluginsDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p pluginsDo) Not(conds ...gen.Condition) *pluginsDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p pluginsDo) Or(conds ...gen.Condition) *pluginsDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p pluginsDo) Select(conds ...field.Expr) *pluginsDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p pluginsDo) Where(conds ...gen.Condition) *pluginsDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p pluginsDo) Order(conds ...field.Expr) *pluginsDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p pluginsDo) Distinct(cols ...field.Expr) *pluginsDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p pluginsDo) Omit(cols ...field.Expr) *pluginsDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p pluginsDo) Join(table schema.Tabler, on ...field.Expr) *pluginsDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p pluginsDo) LeftJoin(table schema.Tabler, on ...field.Expr) *pluginsDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p pluginsDo) RightJoin(table schema.Tabler, on ...field.Expr) *pluginsDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p pluginsDo) Group(cols ...field.Expr) *pluginsDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p pluginsDo) Having(conds ...gen.Condition) *pluginsDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p pluginsDo) Limit(limit int) *pluginsDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p pluginsDo) Offset(offset int) *pluginsDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p pluginsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *pluginsDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p pluginsDo) Unscoped() *pluginsDo {
	return p.withDO(p.DO.Unscoped())
}

func (p pluginsDo) Create(values ...*model.Plugins) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p pluginsDo) CreateInBatches(values []*model.Plugins, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p pluginsDo) Save(values ...*model.Plugins) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p pluginsDo) First() (*model.Plugins, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Plugins), nil
	}
}

func (p pluginsDo) Take() (*model.Plugins, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Plugins), nil
	}
}

func (p pluginsDo) Last() (*model.Plugins, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Plugins), nil
	}
}

func (p pluginsDo) Find() ([]*model.Plugins, error) {
	result, err := p.DO.Find()
	return result.([]*model.Plugins), err
}

func (p pluginsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Plugins, err error) {
	buf := make([]*model.Plugins, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p pluginsDo) FindInBatches(result *[]*model.Plugins, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p pluginsDo) Attrs(attrs ...field.AssignExpr) *pluginsDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p pluginsDo) Assign(attrs ...field.AssignExpr) *pluginsDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p pluginsDo) Joins(fields ...field.RelationField) *pluginsDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p pluginsDo) Preload(fields ...field.RelationField) *pluginsDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p pluginsDo) FirstOrInit() (*model.Plugins, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Plugins), nil
	}
}

func (p pluginsDo) FirstOrCreate() (*model.Plugins, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Plugins), nil
	}
}

func (p pluginsDo) FindByPage(offset int, limit int) (result []*model.Plugins, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p pluginsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p pluginsDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p pluginsDo) Delete(models ...*model.Plugins) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *pluginsDo) withDO(do gen.Dao) *pluginsDo {
	p.DO = *do.(*gen.DO)
	return p
}
