// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"blog/dal/model"
)

func newRelationships(db *gorm.DB, opts ...gen.DOOption) relationships {
	_relationships := relationships{}

	_relationships.relationshipsDo.UseDB(db, opts...)
	_relationships.relationshipsDo.UseModel(&model.Relationships{})

	tableName := _relationships.relationshipsDo.TableName()
	_relationships.ALL = field.NewAsterisk(tableName)
	_relationships.Cid = field.NewInt64(tableName, "cid")
	_relationships.Mid = field.NewInt64(tableName, "mid")

	_relationships.fillFieldMap()

	return _relationships
}

type relationships struct {
	relationshipsDo relationshipsDo

	ALL field.Asterisk
	Cid field.Int64
	Mid field.Int64

	fieldMap map[string]field.Expr
}

func (r relationships) Table(newTableName string) *relationships {
	r.relationshipsDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r relationships) As(alias string) *relationships {
	r.relationshipsDo.DO = *(r.relationshipsDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *relationships) updateTableName(table string) *relationships {
	r.ALL = field.NewAsterisk(table)
	r.Cid = field.NewInt64(table, "cid")
	r.Mid = field.NewInt64(table, "mid")

	r.fillFieldMap()

	return r
}

func (r *relationships) WithContext(ctx context.Context) *relationshipsDo {
	return r.relationshipsDo.WithContext(ctx)
}

func (r relationships) TableName() string { return r.relationshipsDo.TableName() }

func (r relationships) Alias() string { return r.relationshipsDo.Alias() }

func (r relationships) Columns(cols ...field.Expr) gen.Columns {
	return r.relationshipsDo.Columns(cols...)
}

func (r *relationships) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *relationships) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 2)
	r.fieldMap["cid"] = r.Cid
	r.fieldMap["mid"] = r.Mid
}

func (r relationships) clone(db *gorm.DB) relationships {
	r.relationshipsDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r relationships) replaceDB(db *gorm.DB) relationships {
	r.relationshipsDo.ReplaceDB(db)
	return r
}

type relationshipsDo struct{ gen.DO }

func (r relationshipsDo) Debug() *relationshipsDo {
	return r.withDO(r.DO.Debug())
}

func (r relationshipsDo) WithContext(ctx context.Context) *relationshipsDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r relationshipsDo) ReadDB() *relationshipsDo {
	return r.Clauses(dbresolver.Read)
}

func (r relationshipsDo) WriteDB() *relationshipsDo {
	return r.Clauses(dbresolver.Write)
}

func (r relationshipsDo) Session(config *gorm.Session) *relationshipsDo {
	return r.withDO(r.DO.Session(config))
}

func (r relationshipsDo) Clauses(conds ...clause.Expression) *relationshipsDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r relationshipsDo) Returning(value interface{}, columns ...string) *relationshipsDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r relationshipsDo) Not(conds ...gen.Condition) *relationshipsDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r relationshipsDo) Or(conds ...gen.Condition) *relationshipsDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r relationshipsDo) Select(conds ...field.Expr) *relationshipsDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r relationshipsDo) Where(conds ...gen.Condition) *relationshipsDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r relationshipsDo) Order(conds ...field.Expr) *relationshipsDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r relationshipsDo) Distinct(cols ...field.Expr) *relationshipsDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r relationshipsDo) Omit(cols ...field.Expr) *relationshipsDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r relationshipsDo) Join(table schema.Tabler, on ...field.Expr) *relationshipsDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r relationshipsDo) LeftJoin(table schema.Tabler, on ...field.Expr) *relationshipsDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r relationshipsDo) RightJoin(table schema.Tabler, on ...field.Expr) *relationshipsDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r relationshipsDo) Group(cols ...field.Expr) *relationshipsDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r relationshipsDo) Having(conds ...gen.Condition) *relationshipsDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r relationshipsDo) Limit(limit int) *relationshipsDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r relationshipsDo) Offset(offset int) *relationshipsDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r relationshipsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *relationshipsDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r relationshipsDo) Unscoped() *relationshipsDo {
	return r.withDO(r.DO.Unscoped())
}

func (r relationshipsDo) Create(values ...*model.Relationships) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r relationshipsDo) CreateInBatches(values []*model.Relationships, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r relationshipsDo) Save(values ...*model.Relationships) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r relationshipsDo) First() (*model.Relationships, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Relationships), nil
	}
}

func (r relationshipsDo) Take() (*model.Relationships, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Relationships), nil
	}
}

func (r relationshipsDo) Last() (*model.Relationships, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Relationships), nil
	}
}

func (r relationshipsDo) Find() ([]*model.Relationships, error) {
	result, err := r.DO.Find()
	return result.([]*model.Relationships), err
}

func (r relationshipsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Relationships, err error) {
	buf := make([]*model.Relationships, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r relationshipsDo) FindInBatches(result *[]*model.Relationships, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r relationshipsDo) Attrs(attrs ...field.AssignExpr) *relationshipsDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r relationshipsDo) Assign(attrs ...field.AssignExpr) *relationshipsDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r relationshipsDo) Joins(fields ...field.RelationField) *relationshipsDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r relationshipsDo) Preload(fields ...field.RelationField) *relationshipsDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r relationshipsDo) FirstOrInit() (*model.Relationships, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Relationships), nil
	}
}

func (r relationshipsDo) FirstOrCreate() (*model.Relationships, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Relationships), nil
	}
}

func (r relationshipsDo) FindByPage(offset int, limit int) (result []*model.Relationships, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r relationshipsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r relationshipsDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r relationshipsDo) Delete(models ...*model.Relationships) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *relationshipsDo) withDO(do gen.Dao) *relationshipsDo {
	r.DO = *do.(*gen.DO)
	return r
}
