// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"blog/dal/model"
)

func newTemplates(db *gorm.DB, opts ...gen.DOOption) templates {
	_templates := templates{}

	_templates.templatesDo.UseDB(db, opts...)
	_templates.templatesDo.UseModel(&model.Templates{})

	tableName := _templates.templatesDo.TableName()
	_templates.ALL = field.NewAsterisk(tableName)
	_templates.K = field.NewString(tableName, "k")
	_templates.V = field.NewString(tableName, "v")

	_templates.fillFieldMap()

	return _templates
}

type templates struct {
	templatesDo templatesDo

	ALL field.Asterisk
	K   field.String
	V   field.String

	fieldMap map[string]field.Expr
}

func (t templates) Table(newTableName string) *templates {
	t.templatesDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t templates) As(alias string) *templates {
	t.templatesDo.DO = *(t.templatesDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *templates) updateTableName(table string) *templates {
	t.ALL = field.NewAsterisk(table)
	t.K = field.NewString(table, "k")
	t.V = field.NewString(table, "v")

	t.fillFieldMap()

	return t
}

func (t *templates) WithContext(ctx context.Context) *templatesDo {
	return t.templatesDo.WithContext(ctx)
}

func (t templates) TableName() string { return t.templatesDo.TableName() }

func (t templates) Alias() string { return t.templatesDo.Alias() }

func (t templates) Columns(cols ...field.Expr) gen.Columns { return t.templatesDo.Columns(cols...) }

func (t *templates) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *templates) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 2)
	t.fieldMap["k"] = t.K
	t.fieldMap["v"] = t.V
}

func (t templates) clone(db *gorm.DB) templates {
	t.templatesDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t templates) replaceDB(db *gorm.DB) templates {
	t.templatesDo.ReplaceDB(db)
	return t
}

type templatesDo struct{ gen.DO }

func (t templatesDo) Debug() *templatesDo {
	return t.withDO(t.DO.Debug())
}

func (t templatesDo) WithContext(ctx context.Context) *templatesDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t templatesDo) ReadDB() *templatesDo {
	return t.Clauses(dbresolver.Read)
}

func (t templatesDo) WriteDB() *templatesDo {
	return t.Clauses(dbresolver.Write)
}

func (t templatesDo) Session(config *gorm.Session) *templatesDo {
	return t.withDO(t.DO.Session(config))
}

func (t templatesDo) Clauses(conds ...clause.Expression) *templatesDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t templatesDo) Returning(value interface{}, columns ...string) *templatesDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t templatesDo) Not(conds ...gen.Condition) *templatesDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t templatesDo) Or(conds ...gen.Condition) *templatesDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t templatesDo) Select(conds ...field.Expr) *templatesDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t templatesDo) Where(conds ...gen.Condition) *templatesDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t templatesDo) Order(conds ...field.Expr) *templatesDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t templatesDo) Distinct(cols ...field.Expr) *templatesDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t templatesDo) Omit(cols ...field.Expr) *templatesDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t templatesDo) Join(table schema.Tabler, on ...field.Expr) *templatesDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t templatesDo) LeftJoin(table schema.Tabler, on ...field.Expr) *templatesDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t templatesDo) RightJoin(table schema.Tabler, on ...field.Expr) *templatesDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t templatesDo) Group(cols ...field.Expr) *templatesDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t templatesDo) Having(conds ...gen.Condition) *templatesDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t templatesDo) Limit(limit int) *templatesDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t templatesDo) Offset(offset int) *templatesDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t templatesDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *templatesDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t templatesDo) Unscoped() *templatesDo {
	return t.withDO(t.DO.Unscoped())
}

func (t templatesDo) Create(values ...*model.Templates) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t templatesDo) CreateInBatches(values []*model.Templates, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t templatesDo) Save(values ...*model.Templates) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t templatesDo) First() (*model.Templates, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Templates), nil
	}
}

func (t templatesDo) Take() (*model.Templates, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Templates), nil
	}
}

func (t templatesDo) Last() (*model.Templates, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Templates), nil
	}
}

func (t templatesDo) Find() ([]*model.Templates, error) {
	result, err := t.DO.Find()
	return result.([]*model.Templates), err
}

func (t templatesDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Templates, err error) {
	buf := make([]*model.Templates, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t templatesDo) FindInBatches(result *[]*model.Templates, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t templatesDo) Attrs(attrs ...field.AssignExpr) *templatesDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t templatesDo) Assign(attrs ...field.AssignExpr) *templatesDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t templatesDo) Joins(fields ...field.RelationField) *templatesDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t templatesDo) Preload(fields ...field.RelationField) *templatesDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t templatesDo) FirstOrInit() (*model.Templates, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Templates), nil
	}
}

func (t templatesDo) FirstOrCreate() (*model.Templates, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Templates), nil
	}
}

func (t templatesDo) FindByPage(offset int, limit int) (result []*model.Templates, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t templatesDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t templatesDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t templatesDo) Delete(models ...*model.Templates) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *templatesDo) withDO(do gen.Dao) *templatesDo {
	t.DO = *do.(*gen.DO)
	return t
}
