// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"blog/dal/model"
)

func newViews(db *gorm.DB, opts ...gen.DOOption) views {
	_views := views{}

	_views.viewsDo.UseDB(db, opts...)
	_views.viewsDo.UseModel(&model.Views{})

	tableName := _views.viewsDo.TableName()
	_views.ALL = field.NewAsterisk(tableName)
	_views.Id = field.NewInt64(tableName, "coid")
	_views.Cid = field.NewInt64(tableName, "cid")
	_views.Ip = field.NewString(tableName, "ip")
	_views.Agent = field.NewString(tableName, "agent")
	_views.CreatedAt = field.NewInt64(tableName, "created_at")

	_views.fillFieldMap()

	return _views
}

type views struct {
	viewsDo viewsDo

	ALL       field.Asterisk
	Id        field.Int64
	Cid       field.Int64
	Ip        field.String
	Agent     field.String
	CreatedAt field.Int64

	fieldMap map[string]field.Expr
}

func (v views) Table(newTableName string) *views {
	v.viewsDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v views) As(alias string) *views {
	v.viewsDo.DO = *(v.viewsDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *views) updateTableName(table string) *views {
	v.ALL = field.NewAsterisk(table)
	v.Id = field.NewInt64(table, "coid")
	v.Cid = field.NewInt64(table, "cid")
	v.Ip = field.NewString(table, "ip")
	v.Agent = field.NewString(table, "agent")
	v.CreatedAt = field.NewInt64(table, "created_at")

	v.fillFieldMap()

	return v
}

func (v *views) WithContext(ctx context.Context) *viewsDo { return v.viewsDo.WithContext(ctx) }

func (v views) TableName() string { return v.viewsDo.TableName() }

func (v views) Alias() string { return v.viewsDo.Alias() }

func (v views) Columns(cols ...field.Expr) gen.Columns { return v.viewsDo.Columns(cols...) }

func (v *views) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *views) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 5)
	v.fieldMap["coid"] = v.Id
	v.fieldMap["cid"] = v.Cid
	v.fieldMap["ip"] = v.Ip
	v.fieldMap["agent"] = v.Agent
	v.fieldMap["created_at"] = v.CreatedAt
}

func (v views) clone(db *gorm.DB) views {
	v.viewsDo.ReplaceConnPool(db.Statement.ConnPool)
	return v
}

func (v views) replaceDB(db *gorm.DB) views {
	v.viewsDo.ReplaceDB(db)
	return v
}

type viewsDo struct{ gen.DO }

func (v viewsDo) Debug() *viewsDo {
	return v.withDO(v.DO.Debug())
}

func (v viewsDo) WithContext(ctx context.Context) *viewsDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v viewsDo) ReadDB() *viewsDo {
	return v.Clauses(dbresolver.Read)
}

func (v viewsDo) WriteDB() *viewsDo {
	return v.Clauses(dbresolver.Write)
}

func (v viewsDo) Session(config *gorm.Session) *viewsDo {
	return v.withDO(v.DO.Session(config))
}

func (v viewsDo) Clauses(conds ...clause.Expression) *viewsDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v viewsDo) Returning(value interface{}, columns ...string) *viewsDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v viewsDo) Not(conds ...gen.Condition) *viewsDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v viewsDo) Or(conds ...gen.Condition) *viewsDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v viewsDo) Select(conds ...field.Expr) *viewsDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v viewsDo) Where(conds ...gen.Condition) *viewsDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v viewsDo) Order(conds ...field.Expr) *viewsDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v viewsDo) Distinct(cols ...field.Expr) *viewsDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v viewsDo) Omit(cols ...field.Expr) *viewsDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v viewsDo) Join(table schema.Tabler, on ...field.Expr) *viewsDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v viewsDo) LeftJoin(table schema.Tabler, on ...field.Expr) *viewsDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v viewsDo) RightJoin(table schema.Tabler, on ...field.Expr) *viewsDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v viewsDo) Group(cols ...field.Expr) *viewsDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v viewsDo) Having(conds ...gen.Condition) *viewsDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v viewsDo) Limit(limit int) *viewsDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v viewsDo) Offset(offset int) *viewsDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v viewsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *viewsDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v viewsDo) Unscoped() *viewsDo {
	return v.withDO(v.DO.Unscoped())
}

func (v viewsDo) Create(values ...*model.Views) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v viewsDo) CreateInBatches(values []*model.Views, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v viewsDo) Save(values ...*model.Views) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v viewsDo) First() (*model.Views, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Views), nil
	}
}

func (v viewsDo) Take() (*model.Views, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Views), nil
	}
}

func (v viewsDo) Last() (*model.Views, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Views), nil
	}
}

func (v viewsDo) Find() ([]*model.Views, error) {
	result, err := v.DO.Find()
	return result.([]*model.Views), err
}

func (v viewsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Views, err error) {
	buf := make([]*model.Views, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v viewsDo) FindInBatches(result *[]*model.Views, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v viewsDo) Attrs(attrs ...field.AssignExpr) *viewsDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v viewsDo) Assign(attrs ...field.AssignExpr) *viewsDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v viewsDo) Joins(fields ...field.RelationField) *viewsDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v viewsDo) Preload(fields ...field.RelationField) *viewsDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v viewsDo) FirstOrInit() (*model.Views, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Views), nil
	}
}

func (v viewsDo) FirstOrCreate() (*model.Views, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Views), nil
	}
}

func (v viewsDo) FindByPage(offset int, limit int) (result []*model.Views, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v viewsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v viewsDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v viewsDo) Delete(models ...*model.Views) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *viewsDo) withDO(do gen.Dao) *viewsDo {
	v.DO = *do.(*gen.DO)
	return v
}
